# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicinas', '0003_cuidadocannabis_nombrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceitecannabis',
            name='marca',
            field=models.ForeignKey(default='value', on_delete=django.db.models.deletion.CASCADE, to='medicinas.Marcas'),
        ),
    ]
